name: WaveMC
version: 4.0.0
authors: [Rafael Auler, Rafael_Auler]
main: net.kombopvp.pvp.KomboPvP2
description: Plugin de PvP do KOMBO
api-version: 1.14
depend: [WaveCore, DecentHolograms, PlaceholderAPI, ajLeaderboards, ViaVersion, TAB, Citizens]

commands:
   spawn:
     aliases: [spawn2]
   skit:
   event:
   tpall:
   admin:
   setwarp:
   discord:
   build:
   stats:
   status:
   finalizarbatalhas:
   givexp:
   limparcache:
   money:
   lastlogin:
   ll:
   report:
   head:
   dueljoin:
   removekit:
   gm:
   invsee:
   clear:
   tphere:
   gamemode:
   lobby:
   hub:
   dinheiro:
   aplicar:
   warpjoin:
   set1v1:
   sendtitle:
   givecoins:
   autosoup:
   pvp:
   macrotest:
   setfeast:
   warpinfo:
   fly:
   kitpvp:
   pinfo:
   givekills:
   givedeaths:
   resetkdr:
   givekit:
   v:
   evento:
   lavainiciar:
   1v1iniciar:
   furia:
   arenainiciar:
   vanish:
   sethologram:
   sc:
      aliases: [staffchat]
   rank:
      aliases: [ranks]
   scoreboard:
      aliases: [score]
   verrank:
      aliases: [profile]
   actionbar:
   
   
   
